### ISSUE TITLE
Select year not working on firefox 44.0.2

### ISSUE THREAD

**Issue by ramrami** [puranjayjain/md-date-time-picker#90]
Click on the year in the header, the years view appear, select a year and click ok. The datepicker close with the following error : 

`TypeError: currentYear.scrollIntoViewIfNeeded is not a function`

**Comment by puranjayjain** [comment]
@ramrami you need to use a polyfill for scrollIntoViewIfNeeded check the docs in the ie section you will find a list of polyfills for ie in it, on the link you will find some for firefox as well. If not try a search for a polyfill for it mdn or github or other source.

**Comment by ramrami** [comment]
ok thanks , used [this one](https://gist.github.com/hsablonniere/2581101) working great 👍

**Comment by puranjayjain** [comment]
Great it worked for you :+1:
